apiToken: ${sm://projects/embassyautomator/secrets/API_TOKEN}
address1: ${sm://projects/embassyautomator/secrets/ADDRESS1}
address2: ${sm://projects/embassyautomator/secrets/ADDRESS2}
userEmail: ${sm://projects/embassyautomator/secrets/USER_MAIL}
userPassword: ${sm://projects/embassyautomator/secrets/USER_PASSWORD}
message: ${sm://projects/embassyautomator/secrets/MESSAGE}
spring:
  docker:
    compose:
      enabled: false
#      file: docker-compose.yml
